### ISSUE TITLE
Create an `Interview` model

### ISSUE THREAD

**Issue by blakesaylor** [TuringAllies/turingAllies#1]
# User Story
As a dev
I want to create an `Interview` model
So that it exists

# Acceptance Criteria
- [x] There is a new model in the `models/` directory
- [x] there is a new table in the `db/schema/` directory called interviews

# Discussion

the `Interview` is the thing that will be created by the form (that doesn't exist yet) when a student/alum comes to the site and adds their interview to be included on the site

# Screenshots/Files/Gifs

(optional)

### next steps

(optional)

#### As always...
Work through the AC above to completion then move it to the next column; if any additional items come up, create a new ticket and add it to the board. Anyone is welcome to make new tickets

**Comment by blakesaylor** [comment]
What all attributes would we like this to have? My first thoughts are:

- Required
  - Position Title
  - Company
  - Frontend, Backend, Fullstack, Other
  - Type of interview (Behavioral, technical, etc.)
  - Round 
  - Length
  - Question(s) asked
- Potential
  - Job posting / link
    - Potential to scrape links to create an s3 document?
  - Salary range (if given)
  - Location
    - Remote? In person? Hybrid?
  - Interviewer (team lead/manager, engineer, recruiter, etc.)

**Comment by MarchandMD** [comment]
@blakesaylor are you getting notifications for this? I missed your original message by a couple of days...
